import type { Metadata } from "next";
import { Geist, Geist_Mono, Anek_Tamil, Anton, Inter, Oswald } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/NavBar";
import StoreProvider from "./components/StoreProvider";
import { ToastContainer } from 'react-toastify';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-inter",
  subsets: ["latin"],
});

const anekTamil = Anek_Tamil({
  variable: "--font-anek-tamil",
  subsets: ["latin"],
});
const anton = Anton({
  weight: "400",
  variable: "--font-anton",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anekTamil.variable} ${anton.variable} ${inter.variable} ${oswald.variable}  antialiased`}
      >
        <StoreProvider>
        <ToastContainer/>

          <NavBar></NavBar>
          {children}


        </StoreProvider>
      </body>
    </html>
  );
}
